import styles from "./cm.module.css";

export const CMSelector = () => (
  <div className={styles.root}>
    <div>This is red</div>
    <div className={styles.test}>This is cyan (scoped class generated by CSS Modules)</div>
    <div className="third-party-classname">This is violet (static class)</div>
  </div>
);
