import styles from "./ve.css";

export const VESelector = () => (
  <div className={styles.root}>
    <div>This is red</div>
    <div className={styles.child}>This is cyan (scoped class generated by Vanilla Extract)</div>
    <div className="third-party-classname">This is violet (static class)</div>
  </div>
);
